In [2]:
import pandas as pd

In [3]:
#loading data
dataset=pd.read_csv("Data.csv")
dataset.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [4]:
#checking null value
dataset.isnull().sum()

id                       0
client_id                0
card_brand               0
card_type                0
card_number              0
expires                  0
cvv                      0
has_chip                 0
num_cards_issued         0
credit_limit             0
acct_open_date           0
year_pin_last_changed    0
card_on_dark_web         0
dtype: int64

In [5]:
#Stat
dataset.describe()

,id,client_id,card_number,cvv,num_cards_issued,year_pin_last_changed
count,6146.000000,6146.000000,6.146000e+03,6146.000000,6146.000000,6146.000000
mean,3072.500000,994.939636,4.820426e+15,506.220794,1.503091,2013.436707
std,1774.341709,578.614626,1.328582e+15,289.431123,0.519191,4.270699
min,0.000000,0.000000,3.001055e+14,0.000000,1.000000,2002.000000
25%,1536.250000,492.250000,4.486365e+15,257.000000,1.000000,2010.000000
50%,3072.500000,992.000000,5.108957e+15,516.500000,1.000000,2013.000000
75%,4608.750000,1495.000000,5.585237e+15,756.000000,2.000000,2017.000000
max,6145.000000,1999.000000,6.997197e+15,999.000000,3.000000,2020.000000

In [6]:
dataset["card_type"].value_counts()

card_type
Debit              3511
Credit             2057
Debit (Prepaid)     578
Name: count, dtype: int64

In [7]:
#lower casing the value from columns
dataset["has_chip"]=dataset["has_chip"].str.lower()
dataset["card_on_dark_web"]=dataset["card_on_dark_web"].str.lower()
dataset.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,yes,2,$24295,09/2002,2008,no
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,yes,2,$21968,04/2014,2014,no
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,yes,2,$46414,07/2003,2004,no
3,42,825,Visa,Credit,4879494103069057,08/2024,693,no,1,$12400,01/2003,2012,no
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,yes,1,$28,09/2008,2009,no

## Feature Engineering

In [8]:
dataset.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,yes,2,$24295,09/2002,2008,no
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,yes,2,$21968,04/2014,2014,no
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,yes,2,$46414,07/2003,2004,no
3,42,825,Visa,Credit,4879494103069057,08/2024,693,no,1,$12400,01/2003,2012,no
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,yes,1,$28,09/2008,2009,no

In [9]:
#Adding column to find out how long ago the pin was changed
dataset["pin_age"]=2026-dataset["year_pin_last_changed"]
dataset.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,yes,2,$24295,09/2002,2008,no,18
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,yes,2,$21968,04/2014,2014,no,12
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,yes,2,$46414,07/2003,2004,no,22
3,42,825,Visa,Credit,4879494103069057,08/2024,693,no,1,$12400,01/2003,2012,no,14
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,yes,1,$28,09/2008,2009,no,17

In [10]:
#deleting the confidential column which cannot be used during data analysis
dataset=dataset.drop(columns=["card_number","cvv"])
dataset.head()

,id,client_id,card_brand,card_type,expires,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age
0,4524,825,Visa,Debit,12/2022,yes,2,$24295,09/2002,2008,no,18
1,2731,825,Visa,Debit,12/2020,yes,2,$21968,04/2014,2014,no,12
2,3701,825,Visa,Debit,02/2024,yes,2,$46414,07/2003,2004,no,22
3,42,825,Visa,Credit,08/2024,no,1,$12400,01/2003,2012,no,14
4,4659,825,Mastercard,Debit (Prepaid),03/2009,yes,1,$28,09/2008,2009,no,17

In [11]:
dataset["expires"]=pd.to_datetime(dataset["expires"])

/var/folders/wg/0h1cx_1s32gds14gb974krgr0000gn/T/ipykernel_23740/1150032418.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset["expires"]=pd.to_datetime(dataset["expires"])

In [12]:
dataset['expire_year'] = dataset['expires'].dt.strftime('%Y')
dataset.head()

,id,client_id,card_brand,card_type,expires,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age,expire_year
0,4524,825,Visa,Debit,2022-12-01,yes,2,$24295,09/2002,2008,no,18,2022
1,2731,825,Visa,Debit,2020-12-01,yes,2,$21968,04/2014,2014,no,12,2020
2,3701,825,Visa,Debit,2024-02-01,yes,2,$46414,07/2003,2004,no,22,2024
3,42,825,Visa,Credit,2024-08-01,no,1,$12400,01/2003,2012,no,14,2024
4,4659,825,Mastercard,Debit (Prepaid),2009-03-01,yes,1,$28,09/2008,2009,no,17,2009

In [13]:
#finding account age 
dataset["expire_year"]=dataset["expire_year"].astype(int)
dataset["account_age"]=2026-dataset["expire_year"]
dataset.head()

,id,client_id,card_brand,card_type,expires,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age,expire_year,account_age
0,4524,825,Visa,Debit,2022-12-01,yes,2,$24295,09/2002,2008,no,18,2022,4
1,2731,825,Visa,Debit,2020-12-01,yes,2,$21968,04/2014,2014,no,12,2020,6
2,3701,825,Visa,Debit,2024-02-01,yes,2,$46414,07/2003,2004,no,22,2024,2
3,42,825,Visa,Credit,2024-08-01,no,1,$12400,01/2003,2012,no,14,2024,2
4,4659,825,Mastercard,Debit (Prepaid),2009-03-01,yes,1,$28,09/2008,2009,no,17,2009,17

In [14]:
dataset=dataset.drop(columns=["client_id","expires"])
dataset.head()

,id,card_brand,card_type,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age,expire_year,account_age
0,4524,Visa,Debit,yes,2,$24295,09/2002,2008,no,18,2022,4
1,2731,Visa,Debit,yes,2,$21968,04/2014,2014,no,12,2020,6
2,3701,Visa,Debit,yes,2,$46414,07/2003,2004,no,22,2024,2
3,42,Visa,Credit,no,1,$12400,01/2003,2012,no,14,2024,2
4,4659,Mastercard,Debit (Prepaid),yes,1,$28,09/2008,2009,no,17,2009,17

In [15]:
#creating a seperate column for a multi card client
dataset["multi_card_client"]=["yes" if x>1 else "no" for x in dataset.num_cards_issued]
dataset.head()

,id,card_brand,card_type,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age,expire_year,account_age,multi_card_client
0,4524,Visa,Debit,yes,2,$24295,09/2002,2008,no,18,2022,4,yes
1,2731,Visa,Debit,yes,2,$21968,04/2014,2014,no,12,2020,6,yes
2,3701,Visa,Debit,yes,2,$46414,07/2003,2004,no,22,2024,2,yes
3,42,Visa,Credit,no,1,$12400,01/2003,2012,no,14,2024,2,no
4,4659,Mastercard,Debit (Prepaid),yes,1,$28,09/2008,2009,no,17,2009,17,no

### Managing credit limit column

In [16]:
dataset['credit_limit'] = dataset['credit_limit'].str.replace('$', '').str.replace(',', '').astype(int)
dataset.head()

,id,card_brand,card_type,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age,expire_year,account_age,multi_card_client
0,4524,Visa,Debit,yes,2,24295,09/2002,2008,no,18,2022,4,yes
1,2731,Visa,Debit,yes,2,21968,04/2014,2014,no,12,2020,6,yes
2,3701,Visa,Debit,yes,2,46414,07/2003,2004,no,22,2024,2,yes
3,42,Visa,Credit,no,1,12400,01/2003,2012,no,14,2024,2,no
4,4659,Mastercard,Debit (Prepaid),yes,1,28,09/2008,2009,no,17,2009,17,no

In [17]:
dataset.credit_limit.describe()

count      6146.000000
mean      14347.493980
std       12014.463884
min           0.000000
25%        7042.750000
50%       12592.500000
75%       19156.500000
max      151223.000000
Name: credit_limit, dtype: float64

In [23]:
#Adding a column for a types of credit limit
conditions= [
    dataset["credit_limit"]<=1000,
    (dataset["credit_limit"]>1000) & (dataset["credit_limit"]<=5000),
    (dataset["credit_limit"]>5000) & (dataset["credit_limit"]<10000),
    dataset["credit_limit"]>=10000
]
choices=["low","medium","high","premium"]

import numpy as np
dataset['limit_category'] = np.select(conditions, choices, default='F')
dataset.head()

,id,card_brand,card_type,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,pin_age,expire_year,account_age,multi_card_client,limit_category
0,4524,Visa,Debit,yes,2,24295,09/2002,2008,no,18,2022,4,yes,premium
1,2731,Visa,Debit,yes,2,21968,04/2014,2014,no,12,2020,6,yes,premium
2,3701,Visa,Debit,yes,2,46414,07/2003,2004,no,22,2024,2,yes,premium
3,42,Visa,Credit,no,1,12400,01/2003,2012,no,14,2024,2,no,premium
4,4659,Mastercard,Debit (Prepaid),yes,1,28,09/2008,2009,no,17,2009,17,no,low

In [24]:
dataset["limit_category"].unique()

array(['premium', 'low', 'high', 'medium'], dtype=object)

## Saving the cleaned file

In [25]:
dataset.to_csv("processed.csv",index=False)